### ISSUE TITLE
Epic: As a user/TA I want a class page so that I can see my registered classes and the documents, grades, announcements, discussion group linked to that course.

### ISSUE THREAD

**Issue by iamlax** [kgehmlich/soen341-group2#95]
User Stories: 
- [x] Feature 1 - Add documents + download
- [x] Feature 2- Add/Remove discussion board
- [x] Feature 3 - Add grades
- [x] Feature 4 - Add/Remove Announcements

Other
- [x] Create function to get list of students/TAs in a given class
 Done Sprint 4:  This method is:  `GetAllUsersInAClass(String TargetClass)`: return `List<User>`
