### ISSUE TITLE
As a TA, I want to add grades for the students in the course so that they can see their results for their assignments, quizzes, tests, exams, etc.

### ISSUE THREAD

**Issue by iamlax** [kgehmlich/soen341-group2#97]
**Tasks**

- [x] Create front-end for grades as TA - 
- [x] Create front-end for grades as Student - 
- [x] Link back end to front end of grades -
- [x] Create back-end for feature -

Points: 21 points
Risk: Low Risk
Priority: High Priority

This is a user story for epic #95
